version: '2'
services:

    splunkftp:
      build: 
        context: .
      image: splunkftp
      container_name: splunkftp
      environment:
      #   - FTP_USER=ftpuser
      #   - FTP_PASS=supersecret
      #   - ONLY_UPLOAD=NO
      #   - PASV_ENABLE=NO
        - SPLUNK_START_ARGS=--accept-license
        - SPLUNK_PASSWORD=Test_1234
      #volumes:
      #  - /var/ftp/:/var/ftp/
      ports:
        - "21:21"
        - "20:20"
        - "8000:8000"
        - "40000-40100:40000-40100"
