version: '3.7'
services:

    splunk:
      # build: 
      #   context: .
      image: splunk/splunk:latest
      container_name: splunk
      environment:
      #   - FTP_USER=ftpuser
      #   - FTP_PASS=supersecret
      #   - ONLY_UPLOAD=NO
      #   - PASV_ENABLE=NO
        - SPLUNK_START_ARGS=--accept-license
        - SPLUNK_PASSWORD=Test_1234
      volumes:
       - ./logdata:/var/logdata/
      # command:
      #   - entrypoint.sh 
      #   - ftp-entrypoint.sh
      ports:
        # - "21:21"
        # - "20:20"
        - "8000:8000"
        - "40000-40100:40000-40100"
